### ISSUE TITLE
Pip version of Flask-Cache not compatible with python3

### ISSUE THREAD

**Issue by exaroth** [thadeusb/flask-cache#87] opened 2014-03-20 14:10 UTC
I'm not sure if this project is still maintained but when i tried using pip'ed version under python 3.4 it returned error 

```
No module named exceptions
```

probably related to fact that python 3 doesn't have it, Github version is working OK though.

**Comment by untitaker** [comment] 2014-03-30 10:20
:+1:, please release a new version.

**Comment by fgimian** [comment] 2014-03-30 23:45
+1 please :smile:

**Comment by Nassty** [comment] 2014-04-12 02:15
bump!

**Comment by brutasse** [comment] 2014-04-16 20:52
Dupe of #72. And #88 is related.

That said, big +1 from me as well.

**Closed as completed** 2014-04-21 13:32 UTC
